spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wisoft
    url: jdbc:mysql://localhost:3306/demo01?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

server:
  port: 8082
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.wisoft.template.entity
